# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 20:19
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usps_code', models.CharField(max_length=2, verbose_name='USPS state abbreviation')),
                ('state_fips_code', models.CharField(max_length=2, verbose_name='State FIPS Code')),
                ('fips_code', models.CharField(max_length=3, verbose_name='FIPS Code')),
                ('county_identifier', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=100)),
                ('name_and_description', models.CharField(max_length=100)),
                ('legal_statistical_description', models.CharField(max_length=2)),
                ('fips_55_class_code', models.CharField(max_length=2)),
                ('feature_class_code', models.CharField(max_length=5)),
                ('functional_status', models.CharField(max_length=1)),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Counties',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fips_code', models.CharField(max_length=2, verbose_name='FIPS Code')),
                ('usps_code', models.CharField(db_index=True, max_length=2, verbose_name='USPS state abbreviation')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('area_description_code', models.CharField(max_length=2)),
                ('feature_class_code', models.CharField(max_length=5)),
                ('functional_status', models.CharField(max_length=1)),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='county',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tigerleaflet.State'),
        ),
    ]
